### PR TITLE
Modernize ac_find_gap.m4

### PR DESCRIPTION
**Pull request by fingolfin**
* drop CONFIGNAME support
* make it possible to compile against future GAP releases with
  compatibility mode turned off

### CODE REVIEW

**Comment by stevelinton** [comment]
I don't have the m4 skills to do a detailed review. A few thoughts:

- are we ready to drop `CONFIGNAME` support? No problem if we are, just checking.
- should there be a master copy of this file either in `GAP` itself, or in the `example` package, rather than different versions of it being replicated into individual packages?
- am I right in thinking this doesn't actually address the issue of sourcing the include-path from 
`sysinfo.gap` yet?

**Comment by fingolfin** [comment]
* `CONFIGNAME` is not supported by GAP 4.9+, so this only affects users using legacy versions of GAP; and among those, the few which use `CONFIGNAME`. And I postulate that these will be less than 5 people, possible 0, all of whom are expert GAP users; and probably nobody will want to use this bleeding edge GAP package with such an old GAP anyway.

* I don't see a good logical place for keeping a master copy of this file; it doesn't really belong into GAP; I used to have the "master copy" in https://github.com/gap-system/PackageMaker but I have now switched that away from using autotools, to a pure `gac` based build system. And ideally, I'd like to switch as many package as possible towards that; for most of them, this will be sufficient (the `io` package is a notable exception).

* The include paths *are* sourced from sysinfo.gap, via `GAP_CPPFLAGS`, and that was the case before, too. But of course the build system must actually make use of that (in many packages that's the case; I did not check if this package already did it, but I probably submitted a patch for it here, too)

**Comment by fingolfin** [comment]
Ah, wait, perhaps you meant that we should have a copy of the .m4 file in the GAP repository; and then modify the autogen.sh scripts of these packages to copy that m4 file over, so that the package always uses the latest? Or something like that?

**Comment by stevelinton** [comment]
> On 22 Nov 2018, at 12:40, Max Horn <notifications@github.com> wrote:
> 
> Ah, wait, perhaps you meant that we should have a copy of the .m4 file in the GAP repository; and then modify the autogen.sh scripts of these packages to copy that m4 file over, so that the package always uses the latest? Or something like that?

Honestly I wasn’t sure. What you describe makes sense. It just seemed odd to be changing it package by package.

	Steve

**Comment by fingolfin** [comment]
Unfortunately, right now we don't have a good alternative to changing it package by package. Even if we came up with one, we'd still have to get all packages to adopt it... :-/

**Review by markuspf — APPROVED** [review]

**Pull request merged**
